name: codekit
description: A development kit for Flutter projects, providing common utilities and extensions.
version: 0.0.8
homepage: https://github.com/venhdev/flutter_codekit
repository: https://github.com/venhdev/flutter_codekit

environment:
  sdk: ">=2.17.0 <4.0.0"

# Add regular dependencies here.
dependencies:
  # path: ^1.8.0

dev_dependencies:
  lints: any
  test: any
